### ISSUE TITLE
JsConsoleDump.java is in the wrong directory

### ISSUE THREAD

**Issue by xkahn** [share-extras/js-console#32] opened 2015-01-15 18:49 UTC
It needs to be moved from javascript-console-repo/source/java/de/fme/jsconsole/JsConsoleDump.java -> javascript-console-repo/src/main/java/de/fme/jsconsole/JsConsoleDump.java 

Until this file is moved, mvn compile will report missing symbols.

**Comment by AFaust** [comment] 2015-01-18 13:53
Duplicate of #30

**Comment by jgoldhammer** [comment] 2015-03-01 17:18
Closed as duplicate...

**Closed by jgoldhammer** 2015-03-01 17:18 UTC
